import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { WDCReader, type ParsedField } from '@rhyster/wow-casc-dbc';

type Handedness='one-hand'|'two-hand'|'main-hand-only'|'off-hand-only'|'unknown';
interface Candidate { source:string; boss:string; difficulty:string; track?:string; itemId:number; itemLevel:number; bonusIds?:number[]; }
interface Mapping { schema:number; clientBuildPrefix:string; requiredTables:string[]; optionalTables:string[]; layouts?:Record<string,string>; notes?:string; }
interface TableStatus { name:string; required:boolean; path?:string; checksum?:string; rows?:number; tableHash?:string; layoutHash?:string; error?:string; }
interface ItemMetadata { itemId:number; name?:string; iconFileDataId?:number; inventoryType?:number; classId?:number; subclassId?:number; handedness:Handedness; }
interface JournalDrop { journalEncounterId:number; itemId:number; difficultyMask:number; factionMask:number; flags:number; }
interface EnhancementProposal { enchantId:number; name:string; iconFileDataId?:number; type:'enchant'; slots:string[]; status:'derived'; }
interface DerivedPackage { schema:3; status:'derived'; clientBuild:string; mapping:string; generatedAt:string; tables:TableStatus[]; items:ItemMetadata[]; journalDrops:JournalDrop[]; enhancements:EnhancementProposal[]; candidates:Candidate[]; diagnostics:string[]; }

const arg=(name:string)=>{const index=process.argv.indexOf(name);return index>=0?process.argv[index+1]:undefined;};
const wowPath=arg('--wow'),proposalPath=arg('--proposals'),proposalIsInput=!!proposalPath&&existsSync(proposalPath),output=arg('--out')||(!proposalIsInput&&proposalPath?proposalPath:join(process.cwd(),'.localsimdash','catalog','db2-derived-variants.json')),db2Dir=arg('--db2-dir'),mappingPath=arg('--mapping')||join(process.cwd(),'tools','db2-casc','mappings','12.1.json');
const number=(field:ParsedField|undefined)=>field?Number(field.data):0;
const string=(field:ParsedField|undefined)=>field&&'string' in field&&field.string?field.string:undefined;
const row=(reader:WDCReader,id:number)=>{const value=reader.getRowData(id);return Array.isArray(value)?value:[];};
const hand=(inventoryType:number):Handedness=>inventoryType===13?'one-hand':inventoryType===17?'two-hand':inventoryType===21?'main-hand-only':inventoryType===22?'off-hand-only':'unknown';
function retailBuild(path:string){const lines=readFileSync(path,'utf8').trim().split(/\r?\n/);const columns=lines.shift()?.split('|').map(x=>x.split('!')[0])||[];const product=columns.indexOf('Product'),version=columns.indexOf('Version');const retail=lines.map(line=>line.split('|')).find(row=>row[product]==='wow');if(!retail||version<0||!retail[version])throw new Error('The selected .build.info does not contain a Retail WoW product row.');return retail[version];}
function sparseName(reader:WDCReader,id:number){const value=reader.getRowData(id);if(!value||Array.isArray(value)||value.type!=='sparse')return undefined;const text=value.data.toString('utf8');const found=text.match(/[\x20-\x7e]{3,}/);return found?.[0];}
function loadTable(name:string,required:boolean):{status:TableStatus;reader?:WDCReader}{const path=db2Dir?[join(db2Dir,`${name}.db2`),join(db2Dir,`${name}.DB2`)].find(existsSync):undefined;if(!path)return {status:{name,required,error:'not extracted'}};try{const buffer=readFileSync(path),reader=new WDCReader(buffer,{detectIsZeroedByData:true});return {status:{name,required,path,checksum:createHash('sha256').update(buffer).digest('hex'),rows:reader.getAllIDs().length,tableHash:reader.tableHash.toString(16),layoutHash:reader.layoutHash.toString(16)},reader};}catch(error){return {status:{name,required,path,error:error instanceof Error?error.message:String(error)}};}}

if(!wowPath){console.error('Usage: npm run catalog:db2:prefill -- --wow <WoW root> --db2-dir <exported DB2 folder> [--out <derived package>]');process.exitCode=1;}else try {
  const root=resolve(wowPath),buildInfo=[join(root,'.build.info'),join(root,'_retail_','.build.info')].find(existsSync);if(!buildInfo)throw new Error('No .build.info found in the configured Retail folder.');
  const build=retailBuild(buildInfo),mapping=JSON.parse(readFileSync(mappingPath,'utf8')) as Mapping;if(!build.includes(mapping.clientBuildPrefix))throw new Error(`Client build '${build}' is not supported by mapping '${mapping.clientBuildPrefix}'.`);
  const loaded=[...mapping.requiredTables.map(name=>loadTable(name,true)),...mapping.optionalTables.map(name=>loadTable(name,false))],tables=loaded.map(x=>x.status),readers=new Map(loaded.flatMap(x=>x.reader?[[x.status.name,x.reader] as const]:[]));
  const failed=tables.filter(x=>x.required&&x.error);if(failed.length)throw new Error(`Required DB2 tables unavailable: ${failed.map(x=>`${x.name} (${x.error})`).join(', ')}.`);
  for(const [table,layout] of Object.entries(mapping.layouts||{})){const status=tables.find(x=>x.name===table);if(status?.layoutHash&&status.layoutHash.toLowerCase()!==layout.toLowerCase())throw new Error(`${table} has layout ${status.layoutHash}; mapping expects ${layout}. Update the pinned 12.1 mapping before deriving data.`);}
  const diagnostics=tables.filter(x=>x.error).map(x=>`${x.name}: ${x.error}`),itemReader=readers.get('Item'),sparseReader=readers.get('ItemSparse'),journalReader=readers.get('JournalEncounterItem'),enchantReader=readers.get('SpellItemEnchantment');
  const items:ItemMetadata[]=itemReader?itemReader.getAllIDs().map(itemId=>{const fields=row(itemReader,itemId),inventoryType=number(fields[3]);return {itemId,name:sparseReader?sparseName(sparseReader,itemId):undefined,iconFileDataId:number(fields[6])||undefined,inventoryType,classId:number(fields[0])||undefined,subclassId:number(fields[1])||undefined,handedness:hand(inventoryType)};}):[];
  const journalDrops:JournalDrop[]=journalReader?journalReader.getAllIDs().map(id=>{const fields=row(journalReader,id);return {journalEncounterId:number(fields[1]),itemId:number(fields[2]),factionMask:number(fields[3]),flags:number(fields[4]),difficultyMask:number(fields[5])};}).filter(x=>x.journalEncounterId>0&&x.itemId>0):[];
  const enhancements:EnhancementProposal[]=enchantReader?enchantReader.getAllIDs().map(enchantId=>{const fields=row(enchantReader,enchantId);return {enchantId,name:string(fields[0])||`Enchant ${enchantId}`,iconFileDataId:number(fields[7])||undefined,type:'enchant' as const,slots:[],status:'derived' as const};}):[];
  const candidates=proposalIsInput?JSON.parse(readFileSync(proposalPath!,'utf8')) as Candidate[]:[];for(const x of candidates){if(!x.source||!x.boss||!x.difficulty||!Number.isInteger(x.itemId)||!Number.isInteger(x.itemLevel))throw new Error('Proposal contains an incomplete derived variant.');}
  const result:DerivedPackage={schema:3,status:'derived',clientBuild:build,mapping:mapping.clientBuildPrefix,generatedAt:new Date().toISOString(),tables,items,journalDrops,enhancements,candidates,diagnostics};mkdirSync(resolve(output,'..'),{recursive:true});writeFileSync(output,JSON.stringify(result,null,2));
  console.log(`Derived ${items.length.toLocaleString()} item metadata rows, ${journalDrops.length.toLocaleString()} Journal links, and ${enhancements.length.toLocaleString()} enchantment proposals to ${output}.`);if(diagnostics.length)console.warn(`Partial enhancement coverage: ${diagnostics.join('; ')}`);console.log('All emitted rows are derived only and cannot be simulated until a matching live addon capture promotes a variant to verified.');
} catch(error) { console.error(`DB2/CASC prefill failed: ${error instanceof Error?error.message:String(error)}`); process.exitCode=1; }
