import type { Scenario } from './types.js';

const slots = new Set(['head','neck','shoulder','back','chest','wrist','hands','waist','legs','feet','finger1','finger2','trinket1','trinket2','main_hand','off_hand']);

export function parseProfile(raw: string) {
  const clean = raw.replace(/\r\n/g, '\n').trim();
  const actor = clean.match(/^\s*(death_knight|demon_hunter|druid|evoker|hunter|mage|monk|paladin|priest|rogue|shaman|warlock|warrior)=([^\n]+)/mi);
  if (!actor) throw new Error('This does not look like a SimulationCraft addon export. Include the character class line (for example, warrior=Name).');
  const items = [...clean.matchAll(/^\s*([a-z_0-9]+)=([^\n]+)$/gmi)]
    .filter((m) => slots.has(m[1].toLowerCase()))
    .map((m) => ({ slot: m[1], value: m[2] }));
  const bags = [...clean.matchAll(/^\s*#\s*(?:Gear from Bags|Bags).*$/gmi)];
  return { name: actor[2].trim(), className: actor[1], spec: clean.match(/^\s*spec=([^\n]+)/mi)?.[1]?.trim() || 'unknown', raw: clean, items, bagSections: bags.length };
}

export function scenarioOverlay(s: Scenario) {
  const lines = [
    `fight_style=${s.fightStyle}`,
    `max_time=${s.duration}`,
    `vary_combat_length=${s.variation}`,
    `desired_targets=${s.targets}`,
    `override.bloodlust=${s.bloodlust === 'disabled' ? 0 : 1}`,
    `threads=0`
  ];
  if (s.bloodlust === 'time') lines.push(`bloodlust_time=${s.bloodlustValue ?? 0}`);
  if (s.bloodlust === 'health') lines.push(`bloodlust_percent=${s.bloodlustValue ?? 25}`);
  if (s.bloodlust === 'end') lines.push('bloodlust_time=0');
  if (!s.raidBuffs) lines.push('optimal_raid=0');
  if (!s.consumables) lines.push('default_potion=disabled');
  return lines.join('\n');
}

export function buildInput(profile: string, scenario: Scenario, threads: number) {
  return `${profile.trim()}\n\n# Generated by Local Sim Dashboard\n${scenarioOverlay(scenario)}\nthreads=${threads}\n${scenario.rawOverride.trim()}`.trim() + '\n';
}
