import { StrictMode, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Profile={id:number;name:string;className:string;spec:string;rawProfile:string;createdAt:string};
type Run={id:number;mode:string;title:string;status:string;summary?:string;createdAt:string;scenario:{name:string;targets:number;duration:number}};
const api = async (path:string, init?:RequestInit) => { const r=await fetch(`/api${path}`,init); const body=await r.json().catch(()=>null); if(!r.ok)throw new Error(body?.error||'Request failed'); return body; };
const presets={ 'Single target':{fightStyle:'Patchwerk',targets:1,duration:300}, '2-target cleave':{fightStyle:'Patchwerk',targets:2,duration:300}, '3-target cleave':{fightStyle:'Patchwerk',targets:3,duration:300}, '4-target cleave':{fightStyle:'Patchwerk',targets:4,duration:300}, 'Sustained AoE':{fightStyle:'Patchwerk',targets:8,duration:120} };
const sample=`# SimulationCraft addon export\nwarrior=Example\nlevel=80\nrace=orc\nrole=attack\nspec=fury\ntalents=\nhead=example_helm,id=1\nmain_hand=example_weapon,id=2`;

function App(){
 const [profiles,setProfiles]=useState<Profile[]>([]),[runs,setRuns]=useState<Run[]>([]),[active,setActive]=useState('dashboard'),[paste,setPaste]=useState(''),[notice,setNotice]=useState('');
 const [scenario,setScenario]=useState<any>({name:'Single target',fightStyle:'Patchwerk',duration:300,variation:20,targets:1,bloodlust:'pull',raidBuffs:true,consumables:true,rawOverride:''});
 const [runtime,setRuntime]=useState<any>(); const [threads,setThreads]=useState(1);
 const load=async()=>{ try{const [p,r,h,c]=await Promise.all([api('/profiles'),api('/runs'),api('/health'),api('/config')]);setProfiles(p);setRuns(r);setRuntime(h.runtime);setThreads(c.threads);}catch(e){setNotice((e as Error).message);} }; useEffect(()=>{load();const x=setInterval(load,3000);return()=>clearInterval(x)},[]);
 const selected=profiles[0]; const presetNames=Object.keys(presets);
 const saveProfile=async()=>{try{await api('/profiles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rawProfile:paste})});setPaste('');setNotice('Character imported locally.');load();setActive('dashboard')}catch(e){setNotice((e as Error).message)}};
 const run=async(mode:string)=>{ if(!selected){setActive('import');setNotice('Import a SimulationCraft addon profile first.');return;}try{const r=await api('/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profileId:selected.id,scenario,threads,mode,title:`${selected.name} — ${mode}`})});setNotice(`Run #${r.id} queued locally.`);load();setActive('history')}catch(e){setNotice((e as Error).message)}};
 const scenarioText=useMemo(()=>`fight_style=${scenario.fightStyle}\nmax_time=${scenario.duration}\ndesired_targets=${scenario.targets}\nbloodlust=${scenario.bloodlust}`,[scenario]);
 return <div className="app"><aside><div className="brand"><span>◈</span> LOCAL SIM <b>DASHBOARD</b></div><nav>{[['dashboard','Dashboard'],['import','Import character'],['scenario','Scenario lab'],['topgear','Top Gear'],['droptimizer','Droptimizer'],['compare','Compare & batch'],['history','Run history']].map(([id,label])=><button className={active===id?'active':''} onClick={()=>setActive(id)} key={id}>{label}</button>)}</nav><div className="runtime"><i className={runtime?.available?'ok':'warn'}></i><strong>SIMULATIONCRAFT</strong><small>{runtime?.available?'Runtime ready':'Runtime needed'}</small><small>{runtime?.path||'Set SIMC_PATH or add runtime/simc.exe'}</small></div></aside><main><header><div><p className="eyebrow">YOUR LOCAL THEORYCRAFTING WORKBENCH</p><h1>{active==='dashboard'?'Ready when you are':active.replace(/\b\w/g,c=>c.toUpperCase())}</h1></div><button className="primary" onClick={()=>run('Quick Sim')}>Run quick sim</button></header>{notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
 {active==='dashboard'&&<><section className="hero"><div><p>Import your character, shape the fight, and let SimC work on your machine.</p><div className="buttons"><button className="primary" onClick={()=>setActive('import')}>Import SimC addon export</button><button onClick={()=>setActive('scenario')}>Configure scenario</button></div></div><div className="hero-stat"><b>{profiles.length}</b><span>local character{profiles.length===1?'':'s'}</span><b>{runs.filter(r=>r.status==='completed').length}</b><span>completed runs</span></div></section><section className="grid three">{[['Top Gear','Find the strongest valid gear combination from selected bag items.','topgear'],['Droptimizer','Rank boss and dungeon drops against your active setup.','droptimizer'],['Scenario lab','Control targets, duration, buffs, bloodlust, and raw overrides.','scenario']].map(([t,d,id])=><article className="card" key={t}><h3>{t}</h3><p>{d}</p><button onClick={()=>setActive(id)}>Open {t}</button></article>)}</section><section className="card"><h2>Recent activity</h2><RunTable runs={runs}/></section></>}
 {active==='import'&&<section className="panel"><h2>Import SimulationCraft addon output</h2><p>In-game, run <code>/simc</code>, copy the entire text block, then paste it here. Nothing leaves this computer.</p><textarea value={paste} onChange={e=>setPaste(e.target.value)} placeholder={sample}/><div className="buttons"><button className="primary" onClick={saveProfile}>Validate & save locally</button><button onClick={()=>setPaste(sample)}>Load example</button></div></section>}
 {active==='scenario'&&<section className="split"><div className="panel"><h2>Guided fight setup</h2><label>Preset<select value={scenario.name} onChange={e=>{const p=(presets as any)[e.target.value];setScenario({...scenario,name:e.target.value,...p})}}>{presetNames.map(x=><option>{x}</option>)}</select></label><div className="two"><label>Fight length (sec)<input type="number" value={scenario.duration} onChange={e=>setScenario({...scenario,duration:+e.target.value})}/></label><label>Targets<input type="number" min="1" value={scenario.targets} onChange={e=>setScenario({...scenario,targets:+e.target.value})}/></label></div><label>Bloodlust<select value={scenario.bloodlust} onChange={e=>setScenario({...scenario,bloodlust:e.target.value})}><option value="disabled">Disabled</option><option value="pull">On pull</option><option value="time">At a time</option><option value="health">At target health %</option><option value="end">End of fight</option></select></label><label>Advanced SimC override<textarea className="small" value={scenario.rawOverride} onChange={e=>setScenario({...scenario,rawOverride:e.target.value})} placeholder="Optional raw SimC options..."/></label><button className="primary" onClick={()=>run('Scenario')}>Run this scenario</button></div><div className="panel dark"><p className="eyebrow">GENERATED OVERLAY</p><pre>{scenarioText}</pre><p>Guided controls are appended to the imported profile; raw overrides remain visible and saved with each run.</p></div></section>}
 {['topgear','droptimizer','compare'].includes(active)&&<section className="panel"><p className="eyebrow">{active==='topgear'?'SELECT BAG ITEMS':active==='droptimizer'?'CURATED LOOT SOURCES':'GEAR • TALENTS • BATCH'}</p><h2>{active==='topgear'?'Top Gear':active==='droptimizer'?'Droptimizer':'Compare & batch'}</h2><p>{active==='topgear'?'Select your candidate gear in the imported profile, then start a local ranking run. The completed SimC report is retained with every candidate set.':active==='droptimizer'?'Choose a raid or dungeon source from the bundled loot catalog. Catalog refreshes arrive independently of the app.':'Run named comparisons, talent variants, stat weights, or a batch of scenarios against the active character.'}</p><div className="callout">This screen is wired to the local run queue. Full candidate selection is enabled after importing a profile with bag inventory data.</div><button className="primary" onClick={()=>run(active==='topgear'?'Top Gear':active==='droptimizer'?'Droptimizer':'Compare')}>Start local {active==='topgear'?'ranking':active==='droptimizer'?'loot scan':'comparison'}</button></section>}
 {active==='history'&&<section className="panel"><h2>Local run history</h2><RunTable runs={runs}/></section>}
 </main></div>
}
function RunTable({runs}:{runs:Run[]}){return <div className="runs">{runs.length===0?<p className="muted">No simulations yet.</p>:runs.map(r=><div className="run" key={r.id}><span className={`status ${r.status}`}></span><div><b>{r.title}</b><small>{r.scenario?.targets} target{r.scenario?.targets===1?'':'s'} · {r.scenario?.duration}s · {new Date(r.createdAt).toLocaleString()}</small></div><strong>{r.summary||r.status}</strong>{r.status==='completed'&&<a href={`/api/runs/${r.id}/report`} target="_blank">Report ↗</a>}</div>)}</div>}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
